name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    permissions:
      contents: read
    uses: actionsforge/actions/.github/workflows/node-ci-workflow.yml@main
    with:
      node-version: '20'
      coverage: true
      audit: true
