name: Test Action (Manual)

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'GitHub username to test with'
        required: true
        default: 'test-user'
      token:
        description: 'GitHub token to use for testing'
        required: true
        default: 'test-token'
      limit:
        description: 'Maximum number of repositories to show'
        required: false
        default: '6'
      min-views:
        description: 'Minimum views to skip repositories'
        required: false
        default: '0'
      include-forks:
        description: 'Include forked repositories'
        required: false
        type: boolean
        default: false
      include-archived:
        description: 'Include archived repositories'
        required: false
        type: boolean
        default: false

jobs:
  test-action:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test action
        uses: ./
        with:
          username: ${{ inputs.username }}
          token: ${{ inputs.token }}
          limit: ${{ inputs.limit }}
          min-views: ${{ inputs.min-views }}
          include-forks: ${{ inputs.include-forks }}
          include-archived: ${{ inputs.include-archived }}
